-- CREATE TABLE `User` (
--   `id` BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
--   `name`         VARCHAR(20)  NOT NULL,
--   `username`         VARCHAR(20)  NOT NULL,
--   `password` VARCHAR(20)  NOT NULL,
--   `status` VARCHAR(20)  NOT NULL,
--   `role` VARCHAR(20)  NOT NULL,
--   `email` VARCHAR(20)  NOT NULL,
--   `phone` VARCHAR(20)  NOT NULL
-- );
-- -- username=wer password=war
-- -- INSERT INTO `tw_user` VALUES ( '小明','wer', '$2a$10$EgmhRAlC5iw.KeENZ5.RYebSEHTcO8yl9lOf/r36GoyGb4uNOOhr2','alive','admin','544097676@qq.com','1213545');